global:
  evaluation_interval: 15s
  scrape_interval: 15s

rule_files:
  - "/config/prometheus.rules.yml"

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
        module: [http_2xx]
    static_configs:
        - targets:
                - https://google.com
                - https://microsoft.com
                - https://github.com
                - https://hub.docker.com
    relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox_exporter:9115
