###

# We are using an older samba version here since the newest one causes issues with the smbclient PHP module.
# TODO - security patches are now missing due to this, get rid of this ASAP

FROM schleyk/nginx-php:7.4

RUN apk -U upgrade
RUN apk add --no-cache alpine-sdk git

RUN adduser -g "" -G abuild -k /var/empty -D abuild

WORKDIR /usr/src/aports
RUN chown abuild: /usr/src/aports

USER abuild
RUN abuild-keygen -a -i -n

RUN git clone --recursive -b 3.13-stable https://gitlab.alpinelinux.org/alpine/aports.git .
RUN git checkout cd3147e6c6183d7cbdaf7c7bf2b714aaa8f47af9

RUN cd main/samba && abuild -r

RUN chmod a+rX -R ~/packages

###

FROM schleyk/nginx-php:7.4

ARG NEXTCLOUD_VERSION=21.0.1
ARG NEXTCLOUD_TAG=releases
ARG GPG_nextcloud="2880 6A87 8AE4 23A2 8372  792E D758 99B9 A724 937A"

COPY --from=0 /home/abuild/packages/ /packages/
COPY --from=0 /home/abuild/.abuild/*.pub /etc/apk/keys/
RUN (echo "" && echo "/packages/main/") >> /etc/apk/repositories

ENV UID=991 GID=991 \
    UPLOAD_MAX_SIZE=10G \
    APC_SHM_SIZE=128M \
    OPCACHE_MEM_SIZE=128 \
    MEMORY_LIMIT=512M \
    CRON_PERIOD=15m \
    CRON_MEMORY_LIMIT=1g \
    TZ=Etc/UTC \
    DB_TYPE=sqlite3 \
    DOMAIN=localhost

RUN apk -U upgrade \
 && apk add -t build-dependencies \
    gnupg \
    tar \
    build-base \
    autoconf \
    automake \
    pcre-dev \
    libtool \
    samba-dev=4.13.3-r1 \
 && apk add \
    openssl \
    ca-certificates \
    libsmbclient=4.13.3-r1 \
    tzdata \
 && pecl update-channels \
 && pecl install \
    smbclient \
    apcu \
    redis \
 && echo "extension=smbclient.so" > /php/conf.d/smbclient.ini \
 && echo "extension=redis.so" > /php/conf.d/redis.ini \
 && mkdir /nextcloud \
 && cd /tmp \
 && NEXTCLOUD_TARBALL="nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" \
 && wget -q https://download.nextcloud.com/server/${NEXTCLOUD_TAG}/${NEXTCLOUD_TARBALL} \
 && wget -q https://download.nextcloud.com/server/${NEXTCLOUD_TAG}/${NEXTCLOUD_TARBALL}.sha512 \
 && wget -q https://download.nextcloud.com/server/${NEXTCLOUD_TAG}/${NEXTCLOUD_TARBALL}.asc \
 && wget -q https://nextcloud.com/nextcloud.asc \
 && echo "Verifying both integrity and authenticity of ${NEXTCLOUD_TARBALL}..." \
 && CHECKSUM_STATE=$(echo -n $(sha512sum -c ${NEXTCLOUD_TARBALL}.sha512) | tail -c 2) \
 && if [ "${CHECKSUM_STATE}" != "OK" ]; then echo "Warning! Checksum does not match!" && exit 1; fi \
 && gpg --import nextcloud.asc \
 && FINGERPRINT="$(LANG=C gpg --verify ${NEXTCLOUD_TARBALL}.asc ${NEXTCLOUD_TARBALL} 2>&1 \
  | sed -n "s#Primary key fingerprint: \(.*\)#\1#p")" \
 && if [ -z "${FINGERPRINT}" ]; then echo "Warning! Invalid GPG signature!" && exit 1; fi \
 && if [ "${FINGERPRINT}" != "${GPG_nextcloud}" ]; then echo "Warning! Wrong GPG fingerprint!" && exit 1; fi \
 && echo "All seems good, now unpacking ${NEXTCLOUD_TARBALL}..." \
 && tar xjf ${NEXTCLOUD_TARBALL} --strip 1 -C /nextcloud \
 && update-ca-certificates \
 && apk del build-dependencies \
 && rm -rf /var/cache/apk/* /tmp/*

COPY rootfs21 /

RUN chmod +x /usr/local/bin/* /etc/s6.d/*/* /etc/s6.d/.s6-svscan/*

VOLUME /data /config /apps2 /nextcloud/themes

EXPOSE 8888

LABEL description="A server software for creating file hosting services" \
      nextcloud="Nextcloud v${NEXTCLOUD_VERSION}" \
      maintainer="Schley <info@it-schley.eu>"

CMD ["run.sh"]
