version: '3'

services:
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - UID=1000
      - GID=1000
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=changeme!
      - DB_TYPE=sqlite
    volumes:
      - ./data:/data
      - ./config:/config
      - ./apps:/apps2
    ports:
      - 8888:8888
