############################################
# Possible values: php73, php74, php80
#    build:
#      context: ./bin/${PHPVERSION}
############################################

version: "3"

services:

  web:
    image: schleyk/apache-php:7.4
    restart: 'always'
    ports:
      - "80:80"
    links:
      - db
#      - redis
#      - solr
    volumes:
      - ./www:/var/www/html
      - ./config/cron:/etc/cron.d:ro
      - ./config/sendmail/msmtprc.conf:/etc/msmtprc
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
#      - ./config/openssl/openssl.conf:/usr/lib/ssl/openssl.cnf ## for lagacy MSSQL Connect with TLS1.0

  db:
    image: mariadb:10
    restart: 'always'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme!
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: changeme!
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

#  solr:
#    restart: 'always'
#    image: solr:8.5
#    ports:
#     - "8983:8983"
#    volumes:
#     - solr-data:/var/solr
#    command:
#      - solr-precreate
#      - gettingstarted

#  redis:
#    image: redis:latest

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - db
#    environment:
#      PMA_HOST: db
#    ports:
#      - '8080:80'

#volumes:
#  solr-data:
